### ISSUE TITLE
Webpack Error When Authenticating Signups

### ISSUE THREAD

**Issue by GoodGuyGregory** [Trauma-Troopers/Nursing-App#12]
![Screen Shot 2019-11-04 at 6 57 58 PM](https://user-images.githubusercontent.com/36649901/68167914-40fa3600-ff35-11e9-9c1a-47c6d428c9ce.png)

**Comment by GoodGuyGregory** [comment]
@sventer444  @druss86  I am going to try and scrap the CLI Config Settings. for the User Authentication on Current Dev

**Comment by sventer444** [comment]
@GoodGuyGregory thats fine, do whatever you need to

**Comment by GoodGuyGregory** [comment]
Fixed 🛠
