### ISSUE TITLE
revise git ignore because im sure i messed it up or missed something

### ISSUE THREAD

**Issue by GoodGuyGregory** [Trauma-Troopers/Nursing-App#16]
I am not sure if this is an issue anymore,

Following the standards looked alright with me. I might try to add webpack for the project let me know what you think,

@sventer444

**Comment by GoodGuyGregory** [comment]
@sventer444  I am not having any issues with the local development did you modify the ignore file prior to your last push?

**Comment by sventer444** [comment]
@GoodGuyGregory this was a very old todo item from back when i first initialized the project. haven't had any issues, the intention of the todo was just to double check that everything was okay since you seemed to be confident with gitignores, whereas i only autogenerated it
